model_type: Network3D
attention: false
experiment: WORK_ALONE
rl_framework: DQN
lr: 0.001
gamma: 0.95
max_epsilon: 1.0
min_epsilon: 0.05
decay: 150
agents: 6
tau: 0.01
max_steps: 1
evaluation_steps: 1
episodes: 100
image_interval: 1
evaluation_interval: 5
n_sample_points: 5